Meetings crud
BoostedPenguin/Connfy-Backend pull request #8
Opened 2021-06-11 10:44 UTC by ChrisHadzhikolev

2021-06-11 11:03 UTC, kpuc00 approved these changes

2021-06-11 11:30 UTC, BoostedPenguin requested changes
You're pushing files which need to be ignored.
Also before pushing this to production try hooking it up to android to see if the api calls have any bugs. Translating from JSON to GSON will reveal lots of bugs.

2021-06-16 11:29 UTC, emko203 approved these changes

2021-06-17 18:25 UTC, BoostedPenguin approved these changes

2021-06-17 18:25 UTC, merged